const CatalogMenuData = [
  {
    slug: "chicken_burg",
    title: "Chicken Burger",
    category: "Burger",
    price: 89,
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "white_sauce_pasta",
    title: "White Sauce Pasta",
    price: 89,
    category: "Pasta",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "red_sauce_pasta",
    title: "Red Sauce Pasta",
    price: 89,
    category: "Pasta",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "hakka_noodles",
    title: "Haka Noodles",
    price: 89,
    category: "Noodles",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },

  {
    slug: "steak_burger",
    title: "Steak Burger",
    price: 89,
    category: "Burger",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "italian_style_pizza",
    title: "Italian Style Pizza",
    price: 89,
    category: "Pizza",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "farmhouse_pizza",
    title: "Farmhouse Pizza",
    price: 89,
    category: "Pizza",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "cheese_burger",
    title: "Cheese Burger",
    price: 89,
    category: "Burger",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "chilli_noodles",
    title: "Chilli Noodles",
    price: 89,
    category: "Noodles",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "ramen_noodles",
    title: "Ramen Noodles",
    price: 89,
    category: "Noodles",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "cheese_pizza",
    title: "Cheese Pizza",
    price: 89,
    category: "Pizza",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    slug: "chiken_pizza",
    title: "Chicken Pizza",
    price: 89,
    category: "Pizza",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
];

export default CatalogMenuData;
